services:
  films.list.uptaded.listener:
    class: CacheBundle\EventListener\FilmsListUpdated
    arguments: [ "@films.cacher" ]
    tags:
      - { name: kernel.event_listener, event: films.listed, method: updateFilmsListCache}
      - { name: kernel.event_listener, event: film.edited, method: updateFilmsListCache}
      - { name: kernel.event_listener, event: film.removed, method: updateFilmsListCache}
      - { name: kernel.event_listener, event: film.added, method: updateFilmsListCache}
  films.cacher:
    class: CacheBundle\Services\FilmsCacher
    arguments: [ "@doctrine.orm.entity_manager", "@service_container" ]
  list.films.cache:
    class: CacheBundle\Services\ListFilmsFromCache
    decorates: list.films
    decoration_inner_name: list.films.simple
    arguments: ["@list.films.simple"]
