# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
  films.listed.listener:
     class: CacheBundle\EventListener\FilmsListed
     tags:
        - { name: kernel.event_listener, event: films.listed, method: addFilmsListToCache}
  film.edited.listener:
      class: CacheBundle\EventListener\FilmEdited
      tags:
        - { name: kernel.event_listener, event: film.edited, method: removeCacheAfterFilmEdited}
  film.removed.listener:
      class: CacheBundle\EventListener\FilmRemoved
      tags:
        - { name: kernel.event_listener, event: film.removed, method: removeCacheAfterFilmRemoved}
  film.added.listener:
      class: CacheBundle\EventListener\FilmAdded
      tags:
        - { name: kernel.event_listener, event: film.added, method: removeCacheAfterFilmAdded}
