film_homepage:
    path:     /
    defaults: { _controller: FilmBundle:Default:index }
film_create:
    path:     /film
    defaults: { _controller: FilmBundle:CreateFilm:index }
    methods: [PUT]
film_list:
    path:     /film
    defaults: { _controller: FilmBundle:ListFilms:index }
    methods: [GET]

