film_homepage:
    path:     /
    defaults: { _controller: FilmBundle:Default:index }
film_create:
    path:     /film
    defaults: { _controller: FilmBundle:CreateFilm:index }
    methods: [PUT]
film_list:
    path:     /film
    defaults: { _controller: FilmBundle:ListFilms:index }
    methods: [GET]
film_edit:
    path:     /edit/{id}/film
    defaults: { _controller: FilmBundle:EditFilm:edit }
    methods: [PUT]
film_remove:
    path:     /remove/{id}/film
    defaults: { _controller: FilmBundle:RemoveFilm:remove }
    methods: [DELETE]

