film_homepage:
    path:     /
    defaults: { _controller: FilmBundle:Default:index }
film_create:
    path:     /film
    defaults: { _controller: FilmBundle:CreateFilm:create }
    methods: [POST]
film_list:
    path:     /film
    defaults: { _controller: FilmBundle:ListFilms:list }
    methods: [GET]
film_edit:
    path:     /film/{id}
    defaults: { _controller: FilmBundle:EditFilm:edit }
    methods: [PUT]
film_remove:
    path:     /film/{id}
    defaults: { _controller: FilmBundle:RemoveFilm:remove }
    methods: [DELETE]
client:
    path:     /client
    defaults: { _controller: FilmBundle:Client:client }
