services:
  create.film:
    class: FilmBundle\Services\CreateFilm
    arguments: ["@doctrine.orm.entity_manager"]
#    film.example:
#        class: FilmBundle\Example
#        arguments: ["@service_id", "plain_value", %parameter%]
