services:
  create.film:
    class: FilmBundle\Services\CreateFilm
    arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher"]
  list.films:
    class: FilmBundle\Services\ListFilms
    arguments: ["@doctrine.orm.entity_manager", "@event_dispatcher"]
  edit.film:
    class: FilmBundle\Services\EditFilm
    arguments: ["@doctrine.orm.entity_manager", "@search.film", "@event_dispatcher"]
  search.film:
    class: FilmBundle\Services\SearchFilmById
    arguments: ["@doctrine.orm.entity_manager"]
  remove.film:
    class: FilmBundle\Services\RemoveFilm
    arguments: ["@doctrine.orm.entity_manager", "@search.film","@event_dispatcher"]
  create.film.from.request:
      class: FilmBundle\Services\CreateFilmFromRequest
      arguments: []
