services:
  create.film:
    class: FilmBundle\Services\CreateFilm
    arguments: ["@doctrine.orm.entity_manager"]
  list.films:
      class: FilmBundle\Services\ListFilms
      arguments: ["@doctrine.orm.entity_manager"]
  edit.film:
        class: FilmBundle\Services\EditFilm
        arguments: ["@doctrine.orm.entity_manager","@search.film"]
  search.film:
          class: FilmBundle\Services\SearchFilmById
          arguments: ["@doctrine.orm.entity_manager"]
  remove.film:
          class: FilmBundle\Services\RemoveFilm
          arguments: ["@doctrine.orm.entity_manager","@search.film"]
